	the",be",to",of",and",a",in",that",have",I",it",for",not",on",with",he",as",you",do",at",this",but",his",by",from",they",we",say",her",she",or",an",will",my",one",all",would",there",their",what",so",up",out",if",about",who",get",which",go",me",when",make",can",like",time",no",just",him",know",take",people",into",year",your",good",some",could",them",see",other",than",then",now",look",only",come",its",over",think",also",back",after",use",two",how",our",work",first",well",way",even",new",want",because",any",these",give",day",most",us

"astrophysics",
"astronomy",
"atom",
"beaker",
"biochemistry",
"biology",
"botany",
"Bunsen burner",
"burette",
"cell",
"chemical",
"chemistry",
"climate",
"climatologist",
"control",
"cuvette",
"data",
"datum",
"electricity
"electrochemist",
"element",
"energy",
"entomology",
"evolution",
"experiment",
"fact",
"flask",
"fossil",
"funnel",
"genetics",
"geology",
"geophysics",
"glassware",
"graduated cylinder",
"gravity",
"herpetology",
"hypothesis",
"ichthyology",
"immunology",
"lab",
"laboratory",
"laws",
"lepidoptery",
"magnetism",
"mass",
"matter",
"measure",
'meteorologist",
"meteorology",
"microbiologist",
"microbiology",
"microscope",
"mineral",
"mineralogy",
"molecule",
"motion",
"observe",
"observatory",
"organism",
"ornithology",
"paleontology",
"particle",
"Petri dish",
"phase",
"physical science",
"physics",
"pipette",
"quantum mechanics",
"radiology",
"research",
"retort",
"scale",
"science",
"scientist",
"seismology",
"telescope",
"temperature",
"test tube",
"theory",
"thermometer",
"tissue",
"variable",
"virologist",
"volcanology",
"volume",
"volumetric flask",
"watch glass",
"weather",
"weigh",
"zoology"


"diabetes",
"multiple sclerosis",
"crohn's and colitis",
"lupus",
"rheumatoid rrthritis",
"allergies and asthma",
"celiac disease",
"relapsing polychondritis",
"scleroderma",
"liver disease",
"infectious diseases",
"cancer",
"heart disease"


"artificial intelligence"


["optical character recognition",
"handwriting recognition",
"speech recognition",
"face recognition",
"artificial creativity",
"computer vision",
"virtual reality",
"image processing",
"diagnosis artificial intelligence",
"game artificial intelligence",
"computer bot",
"natural language processing",
"nonlinear control and Robotics",
"artificial life",
"automated reasoning",
"automation",
"biologically inspired computing",
"concept mining",
"data mining",
"knowledge representation",
"semantic Web",
"e-mail spam filtering",
"robotics",
"behavior-based robotics",
"cognitive",
"cybernetics",
"developmental robotics",
"evolutionary robotics",
"hybrid intelligent system",
"intelligent agent",
"intelligent control",
"litigation"]

"proxyUrl": "https://eschoolweb.herokuapp.com/"

